version: "3.7"

networks:
  default:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: DockerFiles/DockerFile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./DockerFiles/Apache/:/etc/apache2/sites-enabled/
      - ./DockerFiles/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    networks:
      - default

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    platform: linux/x86_64
    restart: always
    environment:
      PMA_HOST: db-symfony
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8088:80"

  db-symfony:
    container_name: db-symfony
    image: mysql:8.0.23
    platform: linux/x86_64
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
    ports:
      - 3306:3306
    networks:
      - default

volumes:
  db_app: